apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ITkannadigaru/GitOps.git
    targetRevision: main
    path: base/authservice
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
